### ISSUE TITLE
[BUG] Moving lines not working as intented in visual mode

### ISSUE THREAD

**Issue by Akianonymus** [booperlv/nvim-gomove#10] opened 2022-05-08 15:41 UTC
Here is a screen recording showing the issue:

https://user-images.githubusercontent.com/32216346/167303724-a5574726-fe2d-4bba-a6e6-7501f8af93b7.mp4

Isn't it supposed to move the line because i am in visual mode, not visual block mode. Seems like nvim-gomove somehow changes it to visual block mode. Is this intended ? If so do guide on how to avoid this.

My config is same as the one given in [README.md](https://github.com/booperlv/nvim-gomove#configuration)

**Comment by booperlv** [comment] 2022-05-13 06:57
Apologies for the late reply! This is actually intended behavior. _V_ (Visual Line) is the selection that lets you move lines. I believe I made it this way because of the scenario where you may want to select a word inside a line using _v_ and then move it vertically. This was because I found that I'd use _Ctrl+V_ (Visual Block) pretty exclusively for many lines at once?

However, I do see why this could be the behavior people may desire more and I don't really want to dictate how people do things. It is customizable by making your own mappings as demonstrated in /lua/gomove/mappings/smart.lua, but it would be too much of a hassle for a simple change. So I think I'll make an option for this exact scenario and will be right back.

**Comment by booperlv** [comment] 2022-05-16 05:26
I think I've found a behavior that could work for both use cases! Visual mode moves lines IF the start of the selection is on the start of the line, otherwise moves blocks. I think that can give us the best of both worlds in this regard. I will update this thread if I do change my mind again.

**Comment by booperlv** [comment] 2022-05-18 11:39
In the end, I've chosen to go with the latter behavior, just slightly modified! Now we move a visual selection as a line when the visual selection starts at 0 and if there is more than one line being selected. 4e88aea7a7c2e20c3149ba470d0a34770846cdab! Closing this issue!

**Closed as completed by booperlv** 2022-05-18 11:39 UTC

**Comment by Akianonymus** [comment] 2022-07-26 05:02
I don't think this was solved.


https://user-images.githubusercontent.com/32216346/180927086-f51f90b7-f75e-438e-85f1-638791b6b434.mp4

Basically i wanted the behaviour that is shown in https://github.com/matze/vim-move first video. If i selected the text ,  it should move all the selected text, not according to cursor position or something

**Comment by booperlv** [comment] 2022-08-04 05:32
Hello @Akianonymus! Apologies again for the late reply as I'd been busy with other things, but I'm back with a solution now:)

I won't implement this into the plugin itself, because it is a subjective matter. However, I've made a configuration that achieves what you'd prefer:

I will work on making this simpler in the future, as I am working on a project similar to nvim-gomove, a more flexible version. So refactoring this current code base is lower on my priority list at the moment.

```lua
local M = {}
local silent = {silent=true}
local FILEDIRECTORY = "plugins.move" -- change this to the configuration file directory

require("gomove").setup {
  -- whether or not to map default key bindings, (true/false)
  map_defaults = false,
}

function M.Go(visual, duplicate, block, direction, count)
  local mapping = string.format(
    [[\<Plug>Go%s%s%s%s]],
      (visual and "V" or "N"),
      (duplicate and "D" or "M"),
      (block and "Block" or "Line"),
      direction
  )
  vim.cmd('execute "normal'..count..mapping..'"')
end

-- move
vim.keymap.set('n', '<A-h>', ':<C-u>lua require("'..FILEDIRECTORY..'").Go(false, false, true, "Left", -vim.v.count1)<CR>', silent)
vim.keymap.set('n', '<A-j>', ':<C-u>lua require("'..FILEDIRECTORY..'").Go(false, false, false, "Down", vim.v.count1)<CR>', silent)
vim.keymap.set('n', '<A-k>', ':<C-u>lua require("'..FILEDIRECTORY..'").Go(false, false, false, "Up", -vim.v.count1)<CR>', silent)
vim.keymap.set('n', '<A-l>', ':<C-u>lua require("'..FILEDIRECTORY..'").Go(false, false, true, "Right", vim.v.count1)<CR>', silent)
-- duplicate
vim.keymap.set('n', '<A-S-h>', ':<C-u>lua require("'..FILEDIRECTORY..'").Go(false, true, true, "Left", -vim.v.count1)<CR>', silent)
vim.keymap.set('n', '<A-S-j>', ':<C-u>lua require("'..FILEDIRECTORY..'").Go(false, true, false, "Down", vim.v.count1)<CR>', silent)
vim.keymap.set('n', '<A-S-k>', ':<C-u>lua require("'..FILEDIRECTORY..'").Go(false, true, false, "Up", -vim.v.count1)<CR>', silent)
vim.keymap.set('n', '<A-S-l>', ':<C-u>lua require("'..FILEDIRECTORY..'").Go(false, true, true, "Right", vim.v.count1)<CR>', silent)

-- Visual Horizontal 
function M.VH(duplicate, direction, positive_count)
  vim.cmd('normal! gv')
  if vim.fn.visualmode() == 'V' then
    M.Go(true, duplicate, false, direction, positive_count)
  else
    M.Go(true, duplicate, true, direction, positive_count)
  end
end
-- Visual Vertical
function M.VV(duplicate, direction, positive_count)
  vim.cmd('normal! gv')
  if vim.fn.visualmode() == '' then
    M.Go(true, duplicate, true, direction, positive_count)
  else
    M.Go(true, duplicate, false, direction, positive_count)
  end
end

-- visual move
vim.keymap.set('v', '<A-h>', ':<C-u>lua require("'..FILEDIRECTORY..'").VH(false, "Left", -vim.v.count1)<CR>', silent)
vim.keymap.set('v', '<A-j>', ':<C-u>lua require("'..FILEDIRECTORY..'").VV(false, "Down", vim.v.count1)<CR>', silent)
vim.keymap.set('v', '<A-k>', ':<C-u>lua require("'..FILEDIRECTORY..'").VV(false, "Up", -vim.v.count1)<CR>', silent)
vim.keymap.set('v', '<A-l>', ':<C-u>lua require("'..FILEDIRECTORY..'").VH(false, "Right", vim.v.count1)<CR>', silent)
-- visual duplicate
vim.keymap.set('v', '<A-S-h>', ':<C-u>lua require("'..FILEDIRECTORY..'").VH(true, "Left", -vim.v.count1)<CR>', silent)
vim.keymap.set('v', '<A-S-j>', ':<C-u>lua require("'..FILEDIRECTORY..'").VV(true, "Down", vim.v.count1)<CR>', silent)
vim.keymap.set('v', '<A-S-k>', ':<C-u>lua require("'..FILEDIRECTORY..'").VV(true, "Up", -vim.v.count1)<CR>', silent)
vim.keymap.set('v', '<A-S-l>', ':<C-u>lua require("'..FILEDIRECTORY..'").VH(true, "Right", vim.v.count1)<CR>', silent)

return M
```

**Comment by booperlv** [comment] 2022-08-04 05:43
Hello @Akianonymus! Apologies again for the late reply as I'd been busy with other things, but I'm back with a solution now:)

I will work on making this simpler in the future, as I am working on a project similar to nvim-gomove, a more flexible version. So refactoring this current code base is lower on my priority list at the moment.

I won't implement this into the plugin itself, because it is a subjective matter. However, I've made a configuration that achieves what you'd prefer:

```lua
local M = {}
local silent = {silent=true}
local FILEDIRECTORY = "plugins.move" -- change this to the configuration file directory

require("gomove").setup {
  -- whether or not to map default key bindings, (true/false)
  map_defaults = false,
}

function M.Go(visual, duplicate, block, direction, count)
  local mapping = string.format(
    [[\<Plug>Go%s%s%s%s]],
      (visual and "V" or "N"),
      (duplicate and "D" or "M"),
      (block and "Block" or "Line"),
      direction
  )
  vim.cmd('execute "normal'..count..mapping..'"')
end

-- move
vim.keymap.set('n', '<A-h>', ':<C-u>lua require("'..FILEDIRECTORY..'").Go(false, false, true, "Left", vim.v.count1)<CR>', silent)
vim.keymap.set('n', '<A-j>', ':<C-u>lua require("'..FILEDIRECTORY..'").Go(false, false, false, "Down", vim.v.count1)<CR>', silent)
vim.keymap.set('n', '<A-k>', ':<C-u>lua require("'..FILEDIRECTORY..'").Go(false, false, false, "Up", vim.v.count1)<CR>', silent)
vim.keymap.set('n', '<A-l>', ':<C-u>lua require("'..FILEDIRECTORY..'").Go(false, false, true, "Right", vim.v.count1)<CR>', silent)
-- duplicate
vim.keymap.set('n', '<A-S-h>', ':<C-u>lua require("'..FILEDIRECTORY..'").Go(false, true, true, "Left", vim.v.count1)<CR>', silent)
vim.keymap.set('n', '<A-S-j>', ':<C-u>lua require("'..FILEDIRECTORY..'").Go(false, true, false, "Down", vim.v.count1)<CR>', silent)
vim.keymap.set('n', '<A-S-k>', ':<C-u>lua require("'..FILEDIRECTORY..'").Go(false, true, false, "Up", vim.v.count1)<CR>', silent)
vim.keymap.set('n', '<A-S-l>', ':<C-u>lua require("'..FILEDIRECTORY..'").Go(false, true, true, "Right", vim.v.count1)<CR>', silent)

-- Visual Horizontal 
function M.VH(duplicate, direction, count)
  vim.cmd('normal! gv')
  if vim.fn.visualmode() == 'V' then
    M.Go(true, duplicate, false, direction, count)
  else
    M.Go(true, duplicate, true, direction, count)
  end
end
-- Visual Vertical
function M.VV(duplicate, direction, count)
  vim.cmd('normal! gv')
  if vim.fn.visualmode() == '' then
    M.Go(true, duplicate, true, direction, count)
  else
    M.Go(true, duplicate, false, direction, count)
  end
end

-- visual move
vim.keymap.set('x', '<A-h>', ':<C-u>lua require("'..FILEDIRECTORY..'").VH(false, "Left", vim.v.count1)<CR>', silent)
vim.keymap.set('x', '<A-j>', ':<C-u>lua require("'..FILEDIRECTORY..'").VV(false, "Down", vim.v.count1)<CR>', silent)
vim.keymap.set('x', '<A-k>', ':<C-u>lua require("'..FILEDIRECTORY..'").VV(false, "Up", vim.v.count1)<CR>', silent)
vim.keymap.set('x', '<A-l>', ':<C-u>lua require("'..FILEDIRECTORY..'").VH(false, "Right", vim.v.count1)<CR>', silent)
-- visual duplicate
vim.keymap.set('x', '<A-S-h>', ':<C-u>lua require("'..FILEDIRECTORY..'").VH(true, "Left", vim.v.count1)<CR>', silent)
vim.keymap.set('x', '<A-S-j>', ':<C-u>lua require("'..FILEDIRECTORY..'").VV(true, "Down", vim.v.count1)<CR>', silent)
vim.keymap.set('x', '<A-S-k>', ':<C-u>lua require("'..FILEDIRECTORY..'").VV(true, "Up", vim.v.count1)<CR>', silent)
vim.keymap.set('x', '<A-S-l>', ':<C-u>lua require("'..FILEDIRECTORY..'").VH(true, "Right", vim.v.count1)<CR>', silent)

return M
```

**Comment by Akianonymus** [comment] 2022-08-04 11:29
Thank you, that works perfectly for me. Although i have some questions.

Why the `<c-u>` before the lua require, also  what is that symbol in `if vim.fn.visualmode() == '�' then`, renders as a unknown block here.

**Comment by booperlv** [comment] 2022-08-05 06:23
Glad I could help:)

To answer the first question, `<c-u>` is required because when you're in visual mode, entering command mode (pressing ":") shows this `:'<,'>` in the command line. It's showing the marks ['<](https://vimhelp.org/motion.txt.html#%27%3C) and ['>](https://vimhelp.org/motion.txt.html#%27%3E) which contain the start and end positions of the selection in visual mode. Pressing "\<c-u\>"/"ctrl+u" clears this, and leaves you with an empty command line `:` - making it possible to do the lua require.

For the second question, it's ctrl+v [inserted literally](https://vimhelp.org/insert.txt.html#i_CTRL-V). It represents visual block mode in the visualmode() function. [The help page for the function shows when the function returns that value](https://vimhelp.org/builtin.txt.html#visualmode%28%29).
